export interface SearchItem {
  id: number;
  name: string;
  description: string;
}

export const dummyData: SearchItem[] = [
  { id: 1, name: "React", description: "A JavaScript library for building user interfaces" },
  { id: 2, name: "TypeScript", description: "A typed superset of JavaScript" },
  { id: 3, name: "Vite", description: "Next Generation Frontend Tooling" },
  { id: 4, name: "shadcn/ui", description: "Beautifully designed components built with Radix UI and Tailwind CSS" },
  { id: 5, name: "Tailwind CSS", description: "A utility-first CSS framework" },
  { id: 6, name: "Next.js", description: "The React Framework for Production" },
  { id: 7, name: "GraphQL", description: "A query language for APIs" },
  { id: 8, name: "Node.js", description: "JavaScript runtime built on Chrome's V8 JavaScript engine" },
  { id: 9, name: "Express", description: "Fast, unopinionated, minimalist web framework for Node.js" },
  { id: 10, name: "MongoDB", description: "The application data platform" },
  { id: 11, name: "PostgreSQL", description: "The world's most advanced open source database" },
  { id: 12, name: "Docker", description: "Empowering App Development for Developers" },
  { id: 13, name: "Kubernetes", description: "Production-Grade Container Orchestration" },
  { id: 14, name: "AWS", description: "Amazon Web Services, on-demand cloud computing platforms" },
  { id: 15, name: "Azure", description: "Microsoft's cloud computing platform" },
  { id: 16, name: "Google Cloud", description: "Suite of cloud computing services" },
  { id: 17, name: "Redux", description: "A Predictable State Container for JS Apps" },
  { id: 18, name: "Vue.js", description: "The Progressive JavaScript Framework" },
  { id: 19, name: "Angular", description: "Platform for building mobile and desktop web applications" },
  { id: 20, name: "Svelte", description: "Cybernetically enhanced web apps" },
  { id: 21, name: "React Native", description: "A framework for building native apps using React" },
  { id: 22, name: "Django", description: "A high-level Python web framework" },
  { id: 23, name: "Flask", description: "A micro web framework written in Python" },
  { id: 24, name: "Spring Boot", description: "Framework for Java-based applications" },
  { id: 25, name: "Hibernate", description: "A framework for Java-based ORM" },
  { id: 26, name: "Ruby on Rails", description: "A web-application framework written in Ruby" },
  { id: 27, name: "Laravel", description: "A PHP framework for web artisans" },
  { id: 28, name: "Symfony", description: "A set of reusable PHP components and framework" },
  { id: 29, name: "NestJS", description: "A progressive Node.js framework for building efficient applications" },
  { id: 30, name: "Sass", description: "A CSS preprocessor" },
  { id: 31, name: "LESS", description: "A backward-compatible language extension for CSS" },
  { id: 32, name: "Bootstrap", description: "The most popular HTML, CSS, and JS library in the world" },
  { id: 33, name: "Foundation", description: "A responsive front-end framework" },
  { id: 34, name: "Material UI", description: "React components for faster and easier web development" },
  { id: 35, name: "Ant Design", description: "A design system for enterprise-level products" },
  { id: 36, name: "Vuetify", description: "Material Design Component Framework for Vue.js" },
  { id: 37, name: "Bulma", description: "A modern CSS framework based on Flexbox" },
  { id: 38, name: "Chakra UI", description: "A simple, modular, and accessible component library" },
  { id: 39, name: "Gatsby", description: "Blazing fast modern site generator for React" },
  { id: 40, name: "Jest", description: "Delightful JavaScript Testing Framework" },
  { id: 41, name: "Mocha", description: "A feature-rich JavaScript test framework" },
  { id: 42, name: "Cypress", description: "Fast, easy, and reliable testing for anything that runs in a browser" },
  { id: 43, name: "Puppeteer", description: "Headless Chrome Node.js API" },
  { id: 44, name: "Playwright", description: "Node.js library to automate Chromium, Firefox and WebKit" },
  { id: 45, name: "Jasmine", description: "A behavior-driven development framework for testing JavaScript" },
  { id: 46, name: "Karma", description: "A tool that allows you to execute JavaScript code in multiple real browsers" },
  { id: 47, name: "Webpack", description: "A bundler for JavaScript and friends" },
  { id: 48, name: "Parcel", description: "Blazing fast, zero configuration web application bundler" },
  { id: 49, name: "Rollup", description: "A module bundler for JavaScript" },
  { id: 50, name: "Babel", description: "A JavaScript compiler" },
  { id: 51, name: "ESLint", description: "A tool for identifying and reporting on patterns found in ECMAScript/JavaScript code" },
  { id: 52, name: "Prettier", description: "An opinionated code formatter" },
  { id: 53, name: "Turborepo", description: "A high-performance build system for JavaScript and TypeScript codebases" },
  { id: 54, name: "Nx", description: "A set of extensible dev tools for monorepos" },
  { id: 55, name: "Storybook", description: "Frontend workshop for building UI components and pages in isolation" },
  { id: 56, name: "Redux Toolkit", description: "The official, recommended way to write Redux logic" },
  { id: 57, name: "Zustand", description: "A small, fast, and scalable bearbones state-management solution" },
  { id: 58, name: "Recoil", description: "A state management library for React apps" },
  { id: 59, name: "React Query", description: "Hooks for fetching, caching and updating asynchronous data in React" },
  { id: 60, name: "Apollo", description: "GraphQL client that enables you to manage both local and remote data" },
  { id: 61, name: "Blitz.js", description: "A full-stack React framework" },
  { id: 62, name: "Remix", description: "A React framework for building full-stack applications" },
  { id: 63, name: "Nuxt.js", description: "The Intuitive Vue Framework" },
  { id: 64, name: "Gridsome", description: "Build lightning-fast websites with Vue.js" },
  { id: 65, name: "Alpine.js", description: "A rugged, minimal framework for composing JavaScript behavior in your HTML" },
  { id: 66, name: "Electron", description: "Build cross-platform desktop apps with JavaScript, HTML, and CSS" },
  { id: 67, name: "Capacitor", description: "Build cross-platform apps with JavaScript and the web" },
  { id: 68, name: "Expo", description: "An open-source platform for making universal native apps" },
  { id: 69, name: "Cordova", description: "Mobile apps with HTML, CSS & JS" },
  { id: 70, name: "Ionic", description: "Cross-Platform Mobile App Development Framework" },
  { id: 71, name: "Tauri", description: "Framework for building tiny, fast binaries for all major desktop platforms" },
  { id: 72, name: "Flutter", description: "UI toolkit for building natively compiled applications" },
  { id: 73, name: "SwiftUI", description: "Declarative framework for building interfaces on Apple platforms" },
  { id: 74, name: "React Native CLI", description: "Command-line interface for React Native" },
  { id: 75, name: "Xamarin", description: "A cross-platform development framework by Microsoft" },
  { id: 76, name: "Unity", description: "A game engine and IDE" },
  { id: 77, name: "Unreal Engine", description: "A game engine" },
  { id: 78, name: "Three.js", description: "JavaScript 3D library" },
  { id: 79, name: "Babylon.js", description: "A JavaScript framework for building 3D games" },
  { id: 80, name: "Phaser", description: "A fast, free, and fun open-source framework for Canvas and WebGL" },
  { id: 81, name: "OpenGL", description: "A cross-language, cross-platform API for rendering 2D and 3D vector graphics" },
  { id: 82, name: "WebGL", description: "JavaScript API for rendering 3D graphics in a browser" },
  { id: 83, name: "A-frame", description: "A web framework for building VR experiences" },
  { id: 84, name: "NextAuth.js", description: "Authentication for Next.js applications" },
  { id: 85, name: "Passport.js", description: "Simple, unobtrusive authentication for Node.js" },
  { id: 86, name: "JWT", description: "JSON Web Token, a compact URL-safe means of representing claims" },
  { id: 87, name: "OAuth", description: "Open standard for access delegation" },
  { id: 88, name: "Okta", description: "Identity and access management service" },
  { id: 89, name: "Auth0", description: "Authentication and authorization as a service" },
  { id: 90, name: "Firebase Auth", description: "Google's authentication system" },
  { id: 91, name: "SuperTokens", description: "A user authentication solution" },
  { id: 92, name: "Clerk", description: "Authentication and user management for web apps" },
  { id: 93, name: "Supabase Auth", description: "Auth layer provided by Supabase" },
  { id: 94, name: "Netlify Identity", description: "Identity service provided by Netlify" },
  { id: 95, name: "Pusher", description: "Real-time messaging service" },
  { id: 96, name: "Socket.io", description: "Real-time bidirectional event-based communication" },
  { id: 97, name: "WebSockets", description: "A protocol providing full-duplex communication channels" },
  { id: 98, name: "Server-Sent Events", description: "Unidirectional messaging from server to client" },
  { id: 99, name: "GraphQL Subscriptions", description: "Real-time GraphQL" },
  { id: 100, name: "Apache Kafka", description: "A distributed event streaming platform" },
];


export const searchApi = {
  search: async (query: string): Promise<SearchItem[]> => {
    // Simulate API delay
    await new Promise(resolve => setTimeout(resolve, 300));

    return dummyData.filter(item =>
      item.name.toLowerCase().includes(query.toLowerCase()) ||
      item.description.toLowerCase().includes(query.toLowerCase())
    );
  }
};